// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldtwhwsfcywuzetqkipo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkdHdod3NmY3l3dXpldHFraXBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODA4NzEsImV4cCI6MjA2NjQ1Njg3MX0.Aeg1waqU2DK7hAXvknzBBAap5TP9TW3fMaItBm85VGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);